"""initial schema: position + farb_position

Revision ID: 5965dec3c693
Revises: 
Create Date: 2026-05-28 13:14:43.018033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5965dec3c693'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_ms', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_level', ['level'], unique=False)
        batch_op.create_index('ix_events_ts_ms', ['ts_ms'], unique=False)

    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('funding_interval_h', sa.Integer(), nullable=False),
    sa.Column('spot_taker_bps', sa.Float(), nullable=False),
    sa.Column('perp_taker_bps', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at_ms', sa.Integer(), nullable=True),
    sa.Column('stopped_at_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index('ix_strategies_status', ['status'], unique=False)

    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('ts_ms', sa.Integer(), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('spot_value', sa.Float(), nullable=False),
    sa.Column('perp_unrealized', sa.Float(), nullable=False),
    sa.Column('perp_realized_cum', sa.Float(), nullable=False),
    sa.Column('funding_cum', sa.Float(), nullable=False),
    sa.Column('fees_cum', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_equity_snapshots_lookup', ['strategy_id', 'ts_ms'], unique=False)

    op.create_table('farb_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('CHECK_MARGIN', 'OPENING_MARGIN', 'OPENING_LONG', 'OPENING_SHORT', 'OPEN', 'CLOSING_SHORT', 'CLOSING_LONG', 'RELEASING_MARGIN', 'CLOSED', 'FAILED', name='farbstate', native_enum=False, length=20), nullable=False),
    sa.Column('state_data', sa.JSON(), nullable=False),
    sa.Column('spot_position_id', sa.Integer(), nullable=True),
    sa.Column('perp_position_id', sa.Integer(), nullable=True),
    sa.Column('margin_position_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['margin_position_id'], ['positions.id'], name='fk_farb_positions_margin_position_id', use_alter=True),
    sa.ForeignKeyConstraint(['perp_position_id'], ['positions.id'], name='fk_farb_positions_perp_position_id', use_alter=True),
    sa.ForeignKeyConstraint(['spot_position_id'], ['positions.id'], name='fk_farb_positions_spot_position_id', use_alter=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farb_positions', schema=None) as batch_op:
        batch_op.create_index('ix_farb_positions_state', ['state'], unique=False)
        batch_op.create_index('ix_farb_positions_strategy', ['strategy_id'], unique=False)

    op.create_table('funding_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('ts_ms', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('annualized_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'coin', 'ts_ms')
    )
    with op.batch_alter_table('funding_rates', schema=None) as batch_op:
        batch_op.create_index('ix_funding_rates_lookup', ['exchange_id', 'coin', 'ts_ms'], unique=False)

    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('has_spot', sa.Boolean(), nullable=False),
    sa.Column('has_perp', sa.Boolean(), nullable=False),
    sa.Column('min_size', sa.Float(), nullable=False),
    sa.Column('tick_size', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'coin')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('instrument', sa.Enum('SPOT', 'PERP', 'COLLATERAL', name='instrument', native_enum=False, length=12), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', 'NONE', name='side', native_enum=False, length=8), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='positionstatus', native_enum=False, length=8), nullable=False),
    sa.Column('farb_position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farb_position_id'], ['farb_positions.id'], name='fk_positions_farb_position_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('ix_positions_farb', ['farb_position_id'], unique=False)

    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('ts_ms', sa.Integer(), nullable=False),
    sa.Column('mark', sa.Float(), nullable=False),
    sa.Column('spot', sa.Float(), nullable=True),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'coin', 'ts_ms')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index('ix_prices_lookup', ['exchange_id', 'coin', 'ts_ms'], unique=False)

    op.create_table('wallet_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('ts_ms', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('ts_ms', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('slippage_bps', sa.Float(), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_accruals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('ts_ms', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funding_accruals')
    op.drop_table('fills')
    op.drop_table('wallet_snapshots')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index('ix_prices_lookup')

    op.drop_table('prices')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('ix_positions_farb')

    op.drop_table('positions')
    op.drop_table('markets')
    with op.batch_alter_table('funding_rates', schema=None) as batch_op:
        batch_op.drop_index('ix_funding_rates_lookup')

    op.drop_table('funding_rates')
    with op.batch_alter_table('farb_positions', schema=None) as batch_op:
        batch_op.drop_index('ix_farb_positions_strategy')
        batch_op.drop_index('ix_farb_positions_state')

    op.drop_table('farb_positions')
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_equity_snapshots_lookup')

    op.drop_table('equity_snapshots')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index('ix_strategies_status')

    op.drop_table('strategies')
    op.drop_table('exchanges')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_ts_ms')
        batch_op.drop_index('ix_events_level')

    op.drop_table('events')
    # ### end Alembic commands ###
