"""add position_funding_accruals table

Revision ID: dc38c9a572da
Revises: 4a8467c8dc49
Create Date: 2026-05-15 19:22:57.428398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc38c9a572da'
down_revision: Union[str, None] = '4a8467c8dc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_funding_accruals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position_funding_accruals', schema=None) as batch_op:
        batch_op.create_index('ix_pfa_position_ts', ['position_id', 'ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position_funding_accruals', schema=None) as batch_op:
        batch_op.drop_index('ix_pfa_position_ts')

    op.drop_table('position_funding_accruals')
    # ### end Alembic commands ###
